import type { Metadata } from 'next';
import type { FC, PropsWithChildren } from 'react';

import { iconFont, suitVariable } from './fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps extends PropsWithChildren {}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html className='min-h-dvh' lang='ko'>
      <body
        className={`${iconFont.variable} ${suitVariable.variable} flex min-h-dvh flex-col font-suit`}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
