import type { Metadata } from 'next';

import { iconFont, suitVariable } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => {
  return (
    <html lang='ko'>
      <body
        className={`${iconFont.variable} ${suitVariable.variable} font-suit`}
      >
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
