import { tv } from 'tailwind-variants';

export const navbar = tv({
  slots: {
    header: [
      'sticky',
      'inset-x-0',
      'top-0',
      'z-40',
      'flex',
      'h-auto',
      'w-full',
      'items-center',
      'bg-gray-light/80',
      'backdrop-blur-lg',
      'border-b',
      'border-default/10',
    ],
    nav: 'relative z-40 mx-auto flex h-16 w-full max-w-screen-lg flex-nowrap items-center justify-between gap-4 px-6',
    toggle:
      'group flex h-full w-6 items-center justify-center rounded-md outline-none md:hidden',
    srOnly: 'sr-only',
    toggleIcon: [
      'w-full',
      'h-full',
      'pointer-events-none',
      'flex',
      'flex-col',
      'items-center',
      'justify-center',
      'text-inherit',
      'transition-opacity',
      'before:content-[""]',
      'before:block',
      'before:h-px',
      'before:w-6',
      'before:bg-current',
      'before:transition-transform',
      'before:duration-150',
      'before:-translate-y-1',
      'before:rotate-0',
      'group-data-[open=true]:before:translate-y-px',
      'group-data-[open=true]:before:rotate-45',
      'after:content-[""]',
      'after:block',
      'after:h-px',
      'after:w-6',
      'after:bg-current',
      'after:transition-transform',
      'after:duration-150',
      'after:translate-y-1',
      'after:rotate-0',
      'group-data-[open=true]:after:translate-y-0',
      'group-data-[open=true]:after:-rotate-45',
    ],
    logo: [
      'flex',
      'flex-grow',
      'basis-0',
      'flex-nowrap',
      'items-center',
      'justify-start',
      'whitespace-nowrap',
      'bg-transparent',
      'text-base',
      'no-underline',
    ],
    content: [
      'flex',
      'h-full',
      'flex-grow',
      'basis-0',
      'flex-nowrap',
      'items-center',
      'gap-4',
      'data-[justify=start]:justify-start',
      'data-[justify=end]:justify-end',
    ],
    item: 'list-none whitespace-nowrap text-base',
    menu: [
      'fixed',
      'bottom-0',
      'left-0',
      'top-16',
      'z-30',
      'flex',
      'flex-col',
      'gap-2',
      'overflow-y-auto',
      'bg-gray-light',
      'transform',
      'md:translate-x-0',
      'md:w-60',
      'transition-all',
      'p-4',
      'border-r',
      'border-default/10',
    ],
    menuItem: [
      'flex',
      'gap-2',
      'items-center',
      'justify-center',
      'flex-col',
      'data-[justify=start]:justify-start',
      'data-[justify=end]:justify-end',
      'flex-grow',
      'basis-0',
      'flex-nowrap',
    ],
  },
  variants: {
    hasMenu: {
      true: {
        header: 'md:ml-60 md:w-[calc(100%-15rem)]',
        menu: 'md:top-0',
      },
    },
  },
  defaultVariants: {
    hasMenu: false,
  },
});
