name: cd

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get version from message
        run: |
          echo "VERSION=$(echo '${{ github.event.head_commit.message }}' | grep -o -E 'v[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_APP_NAME }}:latest,${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_APP_NAME }}:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: ${{ vars.DOCKER_PLATFORMS }}

  create_release_and_trigger_webhook:
    needs: build_and_push
    environment:
      name: Production
      url: ${{ vars.DOMAIN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get version from message
        run: |
          echo "VERSION=$(echo '${{ github.event.head_commit.message }}' | grep -o -E 'v[0-9]+\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV

      - uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.VERSION }}
          generateReleaseNotes: true
          makeLatest: true
